#!/usr/bin/env python
# Licensed under the terms of the GPL v3. See LICENCE for details

import sys
import argparse

from galaxy import Galaxy
from pathfinder import find_path, find_star
import config as conf
try:
    from grid import GalaxyMap
    pil = True
except ImportError as e:
    if "PIL" in e.message:
        pil = False
    else:
        sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Find the path between the "
                                        "star systems in Frontier: Elite II.")
    parser.add_argument(
            "start", type=str,
            help="Starting star system")
    parser.add_argument(
            "end", type=str,
            help="Ending star system")
    parser.add_argument(
            "-r", "--range", type=int, default=conf.RANGE,
            help="Specify jump range (default %dly)" % conf.RANGE)
    parser.add_argument(
            "-n", "--nomap", action="store_true", default=False,
            help="Do not generate map")
    defScreen = str(conf.SCREENWIDTH) + "x" + str(conf.SCREENHEIGHT)
    parser.add_argument(
            "-s", "--screen", type=str, default=defScreen,
            help="Screen size. Default " + defScreen)
    parser.add_argument(
            "-t", "--tiles", type=str, default="",
            help="Map size. Format: WIDTHxHEIGHT")

    args = parser.parse_args()

    jumpRange = args.range
    if (pil):
        pil = not args.nomap
    screen = args.screen.split("x")
    if len(screen) != 2 or not screen[0].isdigit() or not screen[1].isdigit():
        parser.print_usage()
        print("error: argument -s/--screen: Invalid value: '%s'" % args.screen)
        sys.exit(1)
    else:
        scrSize = (int(screen[0]), int(screen[1]))

    mapSize = (0, 0)
    if (len(args.tiles) > 0):
        tilesStr = args.tiles.split("x")
        if len(tilesStr) != 2 or not tilesStr[0].isdigit() or\
                                 not tilesStr[1].isdigit():
            parser.print_usage()
            print("error: argument -t/--tiles: Invalid value: '%s'" %
                        args.tiles)
            sys.exit(1)
        else:
            mapSize = int(tilesStr[0]), int(tilesStr[1])

    # TODO #1: find the stars by the name
    c = Galaxy()
    c.sanityTest()

    start = find_star(c, args.start)
    if (start == None):
        print args.start + " not found!"
        sys.exit(1)

    end = find_star(c, args.end)
    if (end == None):
        print args.end + " not found!"
        sys.exit(1)

    path = find_path(c, start, end, jumpRange)

    prevStep = None
    if path is not None:
        for step in path:
            print(step.name),
            if (prevStep != None):
                print(": (%.3f ly)" % prevStep.distance(step)),

            print
            prevStep = step

    #print find_star(c, "Essquess")

    if (pil):
        map = GalaxyMap(scrSize)

        map.grid = True
        map.labels = False
        map.path = path
        map.pathLabels = True

        if (mapSize == (0, 0)):
            # TODO #2 determine mapSize, so the whole path can be seen
            x = abs(start.coordx - end.coordx) + 1
            y = abs(start.coordy - end.coordy) + 1
            
            cx = int((start.coordx + end.coordx) / 2.0 - 5912)
            cy = int((start.coordy + end.coordy) / 2.0 - 5412)

            mapSize = (max(x, y), max(x, y))

        map.save(c, (cx, cy), mapSize)
